name: 'altair-app Dev'
on:
  push:
    branches:
      - main
    paths:
      - 'nft-studio/**'
      - 'fabric/**' # dependency
      - 'centrifuge-js/**' # dependency
      - '.github/workflows/nft-studio-build-and-deploy.yml' # dependency
      - '.github/workflows/altair-app-deploy-dev.yml'

jobs:
  dev:
    uses: centrifuge/apps/.github/workflows/nft-studio-build-and-deploy.yml@main
    with:
      netlify-alias: ''
      ipfs-gateway: https://altair.mypinata.cloud/
      collator-wss-url: wss://fullnode.development.cntrfg.com
      relay-wss-url: wss://fullnode-relay.development.cntrfg.com
      subscan-url: https://rococo.subscan.io
      whitelisted-accounts: ''
      network: altair
      subquery-url: https://api.subquery.network/sq/centrifuge/pools
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
      netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      netlify-site-id: ${{ secrets.ALTAIR_APP_DEV_NETLIFY_SITE_ID }}
      pinata-api-key: ${{ secrets.PINATA_API_KEY }}
      pinata-secret-api-key: ${{ secrets.PINATA_SECRET_API_KEY }}
