name: 'centrifuge-app Dev'
on:
  push:
    branches:
      - altair-dev-deployments
    paths:
      - 'centrifuge-app/**'
      - 'fabric/**' # dependency
      - 'centrifuge-js/**' # dependency
      - '.github/workflows/nft-studio-build-and-deploy.yml' # dependency
      - '.github/workflows/centrifuge-app-deploy-dev.yml'

jobs:
  dev:
    uses: centrifuge/apps/.github/workflows/nft-studio-build-and-deploy.yml@main
    with:
      netlify-alias: ''
      ipfs-gateway: https://altair.mypinata.cloud/
      collator-wss-url: wss://fullnode.development.cntrfg.com
      relay-wss-url: wss://fullnode-relay.development.cntrfg.com
      subscan-url: https://rococo.subscan.io
      whitelisted-accounts: ''
      network: centrifuge
      subquery-url: https://api.subquery.network/sq/centrifuge/pools
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
      netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      netlify-site-id: ${{ secrets.NFT_STUDIO_DEV_NETLIFY_SITE_ID }
      pinata-api-key: ${{ secrets.PINATA_API_KEY }}
      pinata-secret-api-key: ${{ secrets.PINATA_SECRET_API_KEY }}
