name: 'centrifuge-app Pull request'
on:
  pull_request:
    paths:
      - 'centrifuge-app/**'
      - 'fabric/**' # dependency
      - 'centrifuge-js/**' # dependency
      - '.github/workflows/centrifuge-app-build-and-deploy.yml' # dependency
      - '.github/workflows/centrifuge-app-pull-request.yml'

jobs:
  pull-request:
    uses: centrifuge/apps/.github/workflows/centrifuge-app-build-and-deploy.yml@main
    with:
      netlify-alias: pr-${{ github.event.pull_request.number }}
      ipfs-gateway: https://altair.mypinata.cloud/
      collator-wss-url: wss://fullnode.development.cntrfg.com
      relay-wss-url: wss://fullnode-relay.development.cntrfg.com
      subscan-url: https://rococo.subscan.io
      whitelisted-accounts: ''
      network: centrifuge
      subquery-url: https://api.subquery.network/sq/embrio-tech/centrifuge-subql
      pool-creation-type: immediate
      default-node-url: ''

    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
      netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      netlify-site-id: ${{ secrets.CENTRIFUGE_APP_DEV_NETLIFY_SITE_ID }}
      pinata-api-key: ${{ secrets.PINATA_API_KEY }}
      pinata-secret-api-key: ${{ secrets.PINATA_SECRET_API_KEY }}
